---
# Kamailio configuration
kamailio_host: 127.0.0.1
kamailio_sip_secret: "1234"
kamailio_sip_account_name_prefix: mediagw
kamailio_enable_tls: "{{ lookup('env','ENABLE_TLS') | bool | default('false') }}"

# Coturn configuration
turn_host: 127.0.0.1
turn_port: 3478
stun_user: dmo
stun_password: "1234"

# Gateway configuration
gateway_image_name: renater/sipmediagw
gateway_image_tag: 1.1.1
gateway_cpu_cores_per_gateway: 2.5

# Option to start gateways at the end of the execution
start_gateways_at_execution: false
start_gateways_maximum: 8
