---
- name: Install gnupg2
  become: true
  apt:
    name: gnupg2
    update_cache: true

- name: Add Kamailio GPG apt Key
  become: true
  apt_key:
    url: http://deb.kamailio.org/kamailiodebkey.gpg
    state: present

- name: Add Kamailio Repository
  become: true
  apt_repository:
    repo: "deb http://deb.kamailio.org/kamailio{{ kamailio_major_version }}{{ kamailio_minor_version }} {{ ansible_distribution_release }} main"
    state: present

- name: Install packages
  become: true
  apt:
    name:
      - kamailio
      - kamailio-tls-modules
      - kamailio-websocket-modules
      - kamailio-python3-modules
      - kamailio-sqlite-modules
      - default-mysql-server
      - python3-pip
    update_cache: true

- name: Install pexpect
  become: true
  pip:
    name: pexpect

- name: Copy configuration files
  become: true
  template:
    src: "{{ item }}.j2"
    dest: "/etc/kamailio/{{ item }}"
  notify: Restart Kamailio
  loop:
    - kamailio.cfg
    - kamctlrc
    - tls.cfg
    - request_gw.py
    - sipmediagw.cfg

- name: Create /usr/local/etc/kamailio directory
  become: true
  file:
    path: /usr/local/etc/kamailio
    state: directory
  notify: Restart Kamailio

- name: Check if database already exists
  stat:
    path: /usr/local/etc/kamailio/kamailio.sqlite
  register: database_file

- name: Create Kamailio database if not exists
  become: true
  expect:
    command: /usr/sbin/kamdbctl create
    responses:
      (?i)Install: y
  notify: Restart Kamailio
  when: not database_file.stat.exists
