---
- name: Copy TLS configuration file
  become: true
  ansible.builtin.copy:
    src: tls.cfg
    dest: /etc/kamailio/tls.cfg
    mode: "640"
    owner: kamailio
    group: kamailio
  notify: Restart Kamailio

- name: Create /etc/kamailio/tls directory
  become: true
  ansible.builtin.file:
    path: /etc/kamailio/tls
    state: directory
    mode: "750"
    owner: kamailio
    group: kamailio
  notify: Restart Kamailio

- name: Copy TLS certificates
  become: true
  ansible.builtin.copy:
    content: "{{ kamailio_file.content }}"
    dest: "/etc/kamailio/tls/{{ kamailio_file.file }}"
    mode: "640"
    owner: kamailio
    group: kamailio
  notify: Restart Kamailio
  loop:
    - content: "{{ fullchain_certificate }}"
      file: cert.pem
    - content: "{{ privkey_certificate }}"
      file: key.pem
  loop_control:
    label: "{{ item.file }}"
    loop_var: kamailio_file
