---
- name: Install Coturn
  become: true
  apt:
    pkg: coturn
    state: present

- name: Ensure Coturn is enabled
  become: true
  lineinfile:
    dest: /etc/default/coturn
    line: TURNSERVER_ENABLED=1
    regexp: "^#?TURNSERVER_ENABLED="

- name: Copy configuration template
  become: true
  template:
    src: turnserver.conf.j2
    dest: /etc/turnserver.conf
  notify: Restart Coturn
