---
- name: Configure Python for the HTTP launcher
  ansible.builtin.include_tasks: python.yml

- name: Pull the Gateway Docker image
  become: true
  community.docker.docker_image:
    name: "{{ gateway_image }}"
    state: present
    source: pull

- name: Copy the launcher deployment files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /var/launcher/{{ item }}
    owner: gateway
    group: gateway
    mode: 0644
  loop:
    - HTTPLauncher.py
    - docker-compose.yml

- name: Copy the launcher script
  become: true
  ansible.builtin.copy:
    src: SIPMediaGW.sh
    dest: /var/launcher/SIPMediaGW.sh
    owner: gateway
    group: gateway
    mode: 0755

- name: Configure the launcher
  become: true
  ansible.builtin.template:
    src: sipmediagw.cfg.j2
    dest: /var/launcher/sipmediagw.cfg
    owner: gateway
    group: gateway
    mode: 0600
