---
- name: Install pip requirements
  become: true
  ansible.builtin.pip:
    name: web.py==0.62
    state: present

- name: Pull the Gateway Docker image
  become: true
  community.docker.docker_image:
    name: "{{ gateway_image }}"
    state: present
    source: pull

- name: Copy the launcher deployment files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /var/launcher/{{ item }}
    owner: gateway
    group: gateway
    mode: 0644
  loop:
    - HTTPLauncher.py
    - docker-compose.yml
    - pm2-ecosystem.yml

- name: Copy the launcher script
  become: true
  ansible.builtin.copy:
    src: SIPMediaGW.sh
    dest: /var/launcher/SIPMediaGW.sh
    owner: gateway
    group: gateway
    mode: 0755

- name: Configure the launcher
  become: true
  ansible.builtin.template:
    src: sipmediagw.cfg.j2
    dest: /var/launcher/sipmediagw.cfg
    owner: gateway
    group: gateway
    mode: 0600

- name: Start the HTTP Launcher with pm2
  ansible.builtin.include_tasks: pm2.yml
