---
- name: Install pip
  become: true
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true

- name: Install pip requirements
  become: true
  ansible.builtin.pip:
    name: web.py==0.62
    state: present
