---
# Scaler Docker image configuration
scaler_image_name: renater/simplescalevm
scaler_version: 3.0.1

# Scaler HTTP configuration
scaler_http_host: 0.0.0.0
scaler_http_port: 8000

# Scaler scaling configuration
scaler_replica_capacity: 1
scaler_replica_min_available_resources: 3
scaler_replica_api_protocol: http
scaler_replica_api_port: 8080
scaler_replica_api_path: /
scaler_replica_api_capacity_key: capacity
scaler_replica_api_termination_key: termination
scaler_external_address_management: false

# Autoscaling configuration
scaler_autoscaling: false

# Provider configuration
scaler_provider: openstack
scaler_provider_configuration:
  auth_url: https://auth.cloud.ovh.net/v3
  username: ovh_user
  password: ovh_password
  region_name: UK1
  project_domain_id: default
  user_domain_name: Default
  project_id: ovh_project_id
  project_name: ovh_project_name
  interface: public
  identity_api_version: 3
  server_name: server
  flavor: d2-8
  image: Debian 11
  ip_version: 4
  network: Ext-Net
  metadata_key: group
  metadata_value: scaled
  floating_ip_description: server
  keypair: ovh_keypair
  use_cloud_init: false
  cloud_init_file: cloud-init.sh
scaler_provider_autoscaling_configuration:
  server_name: autoscaler
  flavor: s1-2
  image: Debian 11
  network: Ext-Net
  metadata_value: autoscaler
  use_cloud_init: false
  cloud_init_file: autoscaler.cloud-init.sh
  nodes: 3

# Gateway Scaler general configuration
scaler_user: scaler
scaler_directory: /var/scaler
scaler_image: "{{ scaler_image_name }}:{{ scaler_provider }}-{{ scaler_version }}"
scaler_container: scaler
