---
# Scaler Docker image configuration
scaler_image_name: renater/simplescalevm
scaler_version: 1.1.0

# Scaler HTTP configuration
scaler_http_host: 0.0.0.0
scaler_http_port: 8000

# Scaler scaling configuration
scaler_replica_capacity: 1
scaler_replica_min_available_resources: 3
scaler_replica_api_protocol: http
scaler_replica_api_port: 8080
scaler_replica_api_path: /
scaler_replica_api_capacity_key: capacity
scaler_replica_api_termination_key: termination

# Provider configuration
scaler_provider: openstack
scaler_provider_configuration:
  auth_url: https://auth.cloud.ovh.net/v3
  username: ovh_user
  password: ovh_password
  region_name: UK1
  project_domain_id: default
  user_domain_name: Default
  project_id: ovh_project_id
  project_name: ovh_project_name
  interface: public
  identity_api_version: 3
  flavor: d2-8
  image: Debian 11
  ip_version: 4
  network: Ext-Net
  metadata_key: group
  metadata_value: scaled
  keypair: ovh_keypair
  cloud_init_file: cloud-init.sh
