---
# Gateway Launcher
gwlauncher_host: 192.168.92.1
gwlauncher_api: "http://{{ gwlauncher_host }}:8080/sipmediagw"

# Coturn
coturn_host: 192.168.92.3
coturn_port: 3478
stun_user: dmo
stun_pass: 1234

# SIP
sip_secret: 1234
