---
- name: Provision the coturn server
  hosts: all
  roles:
    - coturn

- name: Set up the webserver for the status check
  hosts: all
  vars:
    service_name: coturn
  roles:
    - status-checker
