---
- name: Provision the coturn server
  hosts: all
  roles:
    - coturn

- name: Set up the webserver for the status check
  hosts: all
  vars:
    webserver_user: webserver
    webserver_directory: /var/webserver
    service_name: coturn
  roles:
    - status-checker
