---
- name: Configure the gateway user
  hosts: all
  tasks:
    - name: Create the gateway user
      become: true
      ansible.builtin.user:
        name: gateway
        home: /var/launcher

- name: Install and configure Docker
  hosts: all
  become: true
  tasks:
    - name: Install Docker and Docker-compose
      ansible.builtin.include_role:
        name: geerlingguy.docker
      vars:
        docker_users:
          - gateway

    - name: Install pip
      become: true
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: true

    - name: Install Docker pip package
      ansible.builtin.pip:
        name: docker==5.0.3
        state: present

- name: Configure virtual devices
  hosts: all
  roles:
    - virtual-devices

- name: Configure the Gateway Launcher
  hosts: all
  roles:
    - gateway-launcher
