---
- name: Provision the Kamailio server
  hosts: all
  roles:
    - kamailio

- name: Set up the webserver for the status check
  hosts: all
  vars:
    webserver_user: webserver
    webserver_directory: /var/webserver
    service_name: kamailio
  roles:
    - status-checker
