---
- name: Configure the SIP Media Gateway Scaler user
  hosts: all
  tasks:
    - name: Create the Scaler user
      become: true
      ansible.builtin.user:
        name: scaler
        home: /var/scaler

- name: Install and configure Docker
  hosts: all
  become: true
  tasks:
    - name: Install Docker and Docker-compose
      ansible.builtin.include_role:
        name: geerlingguy.docker
      vars:
        docker_users:
          - scaler

    - name: Install pip
      become: true
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: true

    - name: Install Docker & Docker-Compose pip packages
      ansible.builtin.pip:
        name:
          - docker==5.0.3
          - docker-compose==1.29.2
        state: present

- name: Deploy the SIP Media Gateway Scaler
  hosts: all
  tasks:
    - name: Create cloud-init.sh file
      become: true
      ansible.builtin.copy:
        dest: /var/scaler/cloud-init.sh
        content: |
          #!/bin/sh

          echo "Cloud-init executed with success" > /cloud-init.log
        owner: scaler
        group: scaler
        mode: 0600

    - name: Install the scaler
      ansible.builtin.include_role:
        name: scaler
  vars:
    scaler_replica_api_path: /status
    scaler_replica_api_capacity_key: readyToCall
    scaler_replica_api_termination_key: callsEnded
    scaler_provider_configuration:
      auth_url: https://auth.cloud.ovh.net/v3
      username: ovh_user
      password: ovh_password
      region_name: UK1
      project_domain_id: default
      user_domain_name: Default
      project_id: ovh_project_id
      project_name: ovh_project_name
      interface: public
      identity_api_version: 3
      flavor: d2-8
      image: Gateway Host
      ip_version: 4
      network: Ext-Net
      metadata_key: sipmediagw.group
      metadata_value: gateway
      keypair: ovh_keypair
      use_cloud_init: true
      cloud_init_file: cloud-init.sh
