---
- name: Start the HTTP Launcher
  ansible.builtin.command: sudo -u gateway pm2 start /var/launcher/pm2-ecosystem.yml

- name: Save the pm2 configuration
  ansible.builtin.command: sudo -u gateway pm2 save

- name: Configure pm2 automatic start at boot
  become: true
  ansible.builtin.command: pm2 startup systemd -u gateway --hp /var/launcher
