---
- name: Configure the Scaler
  become: true
  ansible.builtin.template:
    src: "{{ scaler_file.src }}"
    dest: "{{ scaler_directory }}/{{ scaler_file.dest }}"
    owner: "{{ scaler_user }}"
    group: "{{ scaler_user }}"
    mode: 0600
  loop:
    - src: env.j2
      dest: .env
    - src: docker-compose.yml.j2
      dest: docker-compose.yml
  loop_control:
    loop_var: scaler_file

- name: Start the Scaler Docker container
  become: true
  become_user: "{{ scaler_user }}"
  community.docker.docker_compose:
    project_src: "{{ scaler_directory }}"
